name: badges
on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: wget https://github.com/go-task/task/releases/download/v3.36.0/task_linux_amd64.deb
    - run: sudo dpkg -i task_linux_amd64.deb
    - run: rm task_linux_amd64.deb

    - run: pip3 install -r requirements-test.txt

    - run: task coverage

    # Add this
    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main